version: '3'
services:
  client:
    build: .
    ports:
      - '3000:3000'

    command: node index.js
    
    depends_on:
      - mongo

      
  mongo:
    image: mongo
    ports:
      - '27017:27017'